name = "workers-project"
type = "javascript"
account_id = "797aa1809556b8ec7444f182a877f35a"
workers_dev = true
compatibility_date = "2021-12-20"

kv_namespaces = [
    { binding = "WP_NSPACE", preview_id = "d40be8479d124f88bdd3d7cd2665d7c7", id = "1a9afd6398a94ad2b604d21f650d0b5c" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
